# Day 4

In [124]:
import pandas as pd

## Step 1: Load and Inspect the Dataset

The dataset was loaded into a Pandas DataFrame using `pd.read_csv()`. After loading, I examined:

- **Shape** to determine the number of rows and columns.
- **Columns** to identify the available features.
- **Data types (`dtypes`)** to understand the type of data stored in each column.

This initial inspection helps understand the dataset before performing any cleaning or analysis.

In [125]:
df = pd.read_csv("train.csv")
print("Shape: ",df.shape)
print("\nColumns: ",df.columns)
print("\ndtypes: ",df.dtypes)

Shape:  (891, 12)

Columns:  Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

dtypes:  PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [126]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [127]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## Step 2: Handle Missing Values

I checked the number of missing values in each column using `isna().sum()`.

The missing values were handled as follows:

- **Age:** Missing values were filled with the **mean age**, since Age is a numerical feature and replacing missing values with the mean preserves most of the information.
- **Cabin:** The entire column was dropped because it contained a large number of missing values, making it less useful for analysis.
- **Embarked:** Missing values were filled with the **most frequent value (mode)** because Embarked is a categorical feature.

After these operations, the dataset no longer contains missing values in the remaining columns.

In [128]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [129]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df=df.drop('Cabin',axis=1)
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [130]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## Step 3: Filter the Dataset

The dataset was filtered to include only passengers whose **Age is greater than 30**.

This filtering creates a subset containing older passengers, allowing analysis of this specific age group. The resulting dataset contains fewer rows than the original, as younger passengers were excluded.

In [131]:
df=df[df['Age']>30]
print(df.shape)
df.head()

(305, 11)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S

## Step 4: Grouping and Aggregation

The data was grouped by the **Sex** column using `groupby()`. For each group, the following statistics were computed:

- **Maximum Age**
- **Average Fare**
- **Most Common Embarkation Port**

These aggregated statistics summarize the characteristics of male and female passengers. Comparing these values helps identify differences between the two groups in terms of age, ticket fare, and the most common embarkation location.

In [132]:
df.groupby("Sex").agg({"Age":"max","Fare":'mean','Embarked':lambda x:x.mode()[0]})

         Age       Fare Embarked
Sex
female  63.0  61.347290        S
male    80.0  32.667656        S

### Interpretation

The data is grouped by passenger sex.

- The maximum age is higher for males than for females.
- The average fare paid by females is higher than that of males.
- The most common embarkation port differs (or is the same) between the two groups.

These statistics show differences in age, ticket price, and embarkation patterns between male and female passengers.